[mysqld]
server-id = 2
bind-address = 0.0.0.0
port = 3306
max_connections = 200
default_authentication_plugin = mysql_native_password

# Настройки репликации (Slave)
relay-log = relay-bin
relay-log-index = relay-bin.index
log-slave-updates = 1
read-only = 1
super-read-only = 1

# Настройки GTID
gtid-mode = ON
enforce-gtid-consistency = ON

# Параметры для стабильной репликации
slave-parallel-workers = 4
slave-parallel-type = LOGICAL_CLOCK
master_info_repository = TABLE
relay_log_info_repository = TABLE
relay_log_recovery = ON
sync_relay_log = 1
sync_relay_log_info = 1

# Дополнительные настройки
slave_net_timeout = 60
skip_ssl

# Оптимизация
innodb_buffer_pool_size = 128M
innodb_log_file_size = 64M
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

[client]
default-character-set = utf8mb4
