[bastion]
51.250.1.119

[bastion:vars]
ansible_user=user

[webservers]
web-a.ru-central1.internal
web-b.ru-central1.internal

[zabbix]
zabbix.ru-central1.internal

[elk]
elasticsearch.ru-central1.internal
kibana.ru-central1.internal

[elasticsearch]
elasticsearch.ru-central1.internal

[kibana]
kibana.ru-central1.internal

[internal:children]
webservers
zabbix
elk

[internal:vars]
ansible_user=user
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@51.250.1.119"'
